#!/bin/bash

echo "🚀 Manual deployment to cook.windexs.ru"
echo "Please run these commands manually on the server:"
echo ""
echo "1. Connect to server:"
echo "   ssh svr@37.110.51.35 -p 1030"
echo "   Password: 640509040147"
echo ""
echo "2. Navigate to project directory:"
echo "   cd ~/cook"
echo ""
echo "3. Pull latest changes:"
echo "   git pull origin main"
echo ""
echo "4. Install dependencies:"
echo "   npm install"
echo ""
echo "5. Build production version:"
echo "   npm run build:prod"
echo ""
echo "6. Restart PM2 process:"
echo "   pm2 restart windex-cook"
echo ""
echo "7. Check status:"
echo "   pm2 status"
echo "   pm2 logs windex-cook"
echo ""
echo "🌐 Application will be available at: http://cook.windexs.ru:1031"


