name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "SSH_PRIVATE_KEY_FOR_DEPLOY exists: ${{ secrets.SSH_PRIVATE_KEY_FOR_DEPLOY != '' }}"
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
          echo "SSH_PORT: ${{ secrets.SSH_PORT }}"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_DEPLOY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{ secrets.SERVER_IP }} -p ${{secrets.SSH_PORT}} './deploy.sh'
