name: Test without secrets

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        run: |
          echo "Testing build process..."
          npm install
          npm run build:prod
          echo "Build completed successfully!"

      - name: Show environment info
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Files in project:"
          ls -la
